#!/bin/sh
#
# @name Mountain Drone
#
# @type VTOL Tiltrotor
# @class VTOL
#
#
# @output MAIN1 Motor right
# @output MAIN2 Motor left
# @output MAIN3 Motor back
#
# @output AUX1 Tilt servo right & left
# @output AUX2 Tilt servo back
# @output AUX3 Elevon right
# @output AUX4 Elevon left
# @output AUX5 Elevator
# @output AUX7 Rudder

# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.vtol_defaults

param set-default VT_TYPE 1
param set-default VT_MC_ON_FMU 1
param set-default RC_MAP_FLAPS 6
param set-default BAT_SOURCE 0
param set-default BAT1_A_PER_V 36.3675
param set-default BAT1_N_CELLS 6
param set-default BAT1_V_CHARGED 4.2000
param set-default BAT1_V_DIV 18.1000
param set-default BAT1_V_EMPTY 3.3000
param set-default BAT2_A_PER_V 36.3675
param set-default BAT2_V_DIV 18.1000
param set-default CBRK_AIRSPD_CHK 162128
param set-default COM_FLTMODE1 0
param set-default COM_FLTMODE6 3
param set-default COM_RC_LOSS_T 2.0000
param set-default GF_ACTION 0
param set-default GF_MAX_HOR_DIST 2.0000
param set-default GF_MAX_VER_DIST 10.0000
param set-default MC_ROLLRATE_D 0.0080
param set-default MC_ROLLRATE_I 0.3250
param set-default MC_ROLL_P 1.0000
param set-default NAV_RCL_ACT 1
param set-default PWM_AUX_DIS1 1400
param set-default PWM_AUX_DIS5 1500
param set-default PWM_AUX_DIS6 1500
param set-default PWM_AUX_MAX1 2100
param set-default PWM_AUX_MAX2 1600
param set-default PWM_AUX_MAX5 1900
param set-default PWM_AUX_MAX6 1900
param set-default PWM_AUX_MIN1 1400
param set-default PWM_AUX_MIN2 900
param set-default PWM_AUX_MIN5 1100
param set-default PWM_AUX_MIN6 1100
param set-default PWM_MAIN_OUT 1234
param set-default RTL_RETURN_ALT 5.0000
param set-default SENS_EN_MS4525 1
param set-default VT_ARSP_TRANS 20.0000
param set-default VT_TILT_TRANS 0.5000
param set-default VT_TRANS_MIN_TM 3.0000
param set-default VT_TRANS_P2_DUR 3.0000
param set-default VT_TRANS_TIMEOUT 30.0000

set MAV_TYPE 21

set MIXER mountain_drone
set MIXER_AUX mountain_drone

set PWM_OUT 1234
